### ISSUE TITLE
Google maps integration

### ISSUE THREAD

**Issue by JacobHarland** [N0ise9/ITSC-4155-Software-Development#42]
Show location of results on the map

**Comment by N0ise9** [comment]
@JacobHarland is this issue an accident? @aaahmed1 is working on Mapbox in #48, and Google maps would theoretically achieve the same thing, but I'm unsure if we could use both. If we could, how would we make them reference each other? Should we use Google Maps instead of Mapbox? Would using Google Maps API be better / easier than Mapbox? Would Google Maps API have the same features that Mapbox has?
